---
- name: Update Apt
  apt:
    update_cache: yes

- name: Checking essentials
  apt:
    state: present
    name:
    - build-essential
    - curl
    - htop
    - mailutils
    - wget
    - vim
    - libssl-dev
    - unzip
    - zip
    - cowsay



- name: Copy vimrc
  copy:
    src: .vimrc
    dest: /home/{{ ansible_ssh_user }}/.vimrc
